name: Quality-check

on: [push]

jobs:
    checkstyle:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Chmod permissions
              run: sudo chmod +x ./gradlew

            - name: Decode google-services.json
              env:
                GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
              run: echo $GOOGLE_SERVICES_JSON > source/application/google-services.json

            - name: QualityCheck
              run: ./gradlew qualityCheck