name: Upload-Test-Build

on:
  push:
    tags:
      - v1.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Chmod permissions
        run: sudo chmod +x ./gradlew

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > source/application/google-services.json

      - name: Build debug
        run: ./gradlew assembleDebug

      - name: Upload artifact to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: ./gradlew appDistributionUploadDebug

      - uses: actions/upload-artifact@v2
        with:
          name: Save apk
          path: source/application/build/outputs/apk/debug/application-debug.apk